name: Build and Test pipeline
on: [push]
jobs:
  Main:
    runs-on: ubutu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v3
    - name: Set up jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn --batch-mode --update-snapshots test jacoco:report
      
    - name: Coveralls Coverage Report Submission
      run: mvn coveralls:report --define repoToken=${{ secrets.COVERALL_REPO_TOKEN }} 
